name: Build and Deploy frontend

on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: [self-hosted, main]

    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/checkout@v2

      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Run build script
        run: pnpm install && pnpm build
